name-template: '=BTC= co@30 Hearts & Minds v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
exclude-lables:
    - 'ignore changelog'
change-template: '- $TITLE (@$AUTHOR).'

template: |
    Requires [ACE3](https://steamcommunity.com/workshop/filedetails/?id=463939057).

    _[Optionals :](https://github.com/Vdauphin/HeartsAndMinds/files/7565267/All_Hearts_and_Minds_mods.zip)_
    - [CUP units and vehicles mod](https://forums.bistudio.com/topic/179326-community-upgrade-project-cup/), [Community Factions Project](https://steamcommunity.com/workshop/filedetails/?id=1369691841), [Cold War Rearmed III](https://steamcommunity.com/sharedfiles/filedetails/?id=2316343124),
    - [RHS USAF](http://www.rhsmods.org/), [RHS AFRF](http://www.rhsmods.org/), [RHS GREF](http://www.rhsmods.org/), [RHS SAF](http://www.rhsmods.org/), [CSLA Iron Curtain CDLC](https://store.steampowered.com/app/1294440/Arma_3_Creator_DLC_CSLA_Iron_Curtain/)
    - [RDS A2 Civilian Pack mod](https://forums.bistudio.com/topic/170165-rds-a2-civilian-pack/),
    - [3CB Factions](https://steamcommunity.com/sharedfiles/filedetails/?id=1673456286), [Central African Rebels [SFF-R]](https://steamcommunity.com/sharedfiles/filedetails/?id=879843800), [Taliban Force 2021 (RHS & 3CB)](https://steamcommunity.com/workshop/filedetails/?id=2585568796), [Western Sahara CDLC](https://steamcommunity.com/sharedfiles/filedetails/?id=2636962953),
    - [FAP Units (Foes & Allies Pack)](https://steamcommunity.com/sharedfiles/filedetails/?id=656514091), [VETERAN](https://steamcommunity.com/workshop/filedetails/?id=1774055232), [GLOBAL MOBILIZATION - COLD WAR GERMANY CDLC](https://store.steampowered.com/app/1042220/Arma_3_Creator_DLC_Global_Mobilization__Cold_War_Germany/)
    - [The Unsung Vietnam War Mod](https://steamcommunity.com/workshop/filedetails/?id=943001311), [S.O.G. PRAIRIE FIRE CDLC](https://store.steampowered.com/app/1227700/Arma_3_Creator_DLC_SOG_Prairie_Fire/)
    - [Iron Front 3 Lite](https://steamcommunity.com/sharedfiles/filedetails/?id=878977835), [Face of War WW2](https://steamcommunity.com/sharedfiles/filedetails/?id=891433622),
    - [Operation: TREBUCHET](https://steamcommunity.com/sharedfiles/filedetails/?id=769440155), [Operation: TREBUCHET First Contact](https://steamcommunity.com/workshop/filedetails/?id=1572627279).

    [Changelog](https://github.com/Vdauphin/HeartsAndMinds/milestone/74?closed=1):

    - Mission.sqm/Param.hpp not changed.
    $CHANGES
