name-template: '=BTC= co@30 Hearts & Minds v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
exclude-lables:
    - 'ignore changelog'
change-template: '- $TITLE (@$AUTHOR).'

template: |
    Requires [ACE3](http://www.armaholic.com/page.php?id=28557).

    _[Optionals :](https://github.com/Vdauphin/HeartsAndMinds/files/3138932/All.Hearts.and.Minds.mods.zip)_
    - [RHS USAF](http://www.armaholic.com/page.php?id=27149), [RHS AFRF](http://www.armaholic.com/page.php?id=27150), [RHS GREF](http://www.armaholic.com/page.php?id=30998), [RHS SAF](http://www.armaholic.com/page.php?id=32203),
    - [RDS A2 Civilian Pack mod](https://forums.bistudio.com/topic/170165-rds-a2-civilian-pack/),
    - [CUP units and vehicles mod](https://forums.bistudio.com/topic/179326-community-upgrade-project-cup/), [Community Factions Project](https://github.com/tupolov/cfp/releases),
    - [3CB Factions](https://steamcommunity.com/sharedfiles/filedetails/?id=1673456286), [Project OPFOR](https://forums.bistudio.com/topic/193185-project-opfor/), [IWAR: Irregular Warfare mod](http://www.armaholic.com/page.php?id=29772), [Iraqi-Syrian Conflic](http://www.armaholic.com/page.php?id=28406), [Central African Rebels [SFF-R]](http://www.armaholic.com/page.php?id=32465),
    - [FAP Units (Foes & Allies Pack)](http://www.armaholic.com/page.php?id=30706), [VETERAN](https://steamcommunity.com/workshop/filedetails/?id=1132375156),
    - [=BTC= Militia mod](https://forums.bistudio.com/topic/188272-btc-militia-for-a3/#entry2983674), [Taliban Fighters by EricJ](http://www.armaholic.com/page.php?id=29543),
    - [The Unsung Vietnam War Mod](http://www.armaholic.com/page.php?id=29948),
    - [Iron Front 3 Lite](http://www.armaholic.com/page.php?id=24714), [Face of War WW2](http://www.armaholic.com/page.php?id=31945),
    - [Operation: TREBUCHET](http://www.armaholic.com/page.php?id=28614), [OPCAN - OPTRE Reskin Pack](http://www.armaholic.com/page.php?id=29718).

    [Changelog](https://github.com/Vdauphin/HeartsAndMinds/milestone/51?closed=1):

    - Mission.sqm/Param.hpp not changed.
    $CHANGES