// Generated by: "Default" call BIS_fnc_exportGUIBaseClasses;

// Control types
#define CT_STATIC           0
#define CT_PROGRESS         8
#define CT_CONTROLS_GROUP   15


// Static styles
#define ST_LEFT           0x00
#define ST_CENTER         0x02

#define ST_MULTI          0x10

// progress bar
#define ST_VERTICAL       0x01
#define ST_HORIZONTAL     0

// Default text sizes
#define GUI_GRID_WAbs           ((safezoneW / safezoneH) min 1.2)
#define GUI_GRID_HAbs           (GUI_GRID_WAbs / 1.2)
#define GUI_GRID_W          (GUI_GRID_WAbs / 40)
#define GUI_GRID_H          (GUI_GRID_HAbs / 25)

// Default text sizes
#define GUI_TEXT_SIZE_MEDIUM        (GUI_GRID_H * 1)

class ScrollBar {
    color[] = {1,1,1,0.6};
    colorActive[] = {1,1,1,1};
    colorDisabled[] = {1,1,1,0.3};
    width = 0;
    height = 0;
    autoScrollEnabled = 0;
    autoScrollSpeed = -1;
    autoScrollDelay = 5;
    autoScrollRewind = 0;
    thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
    arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
    arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
    border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
    shadow = 0;
    scrollSpeed = 0.06;
};
class IGUIBack {
   type = CT_STATIC;
   idc = -1;
   style = ST_CENTER;
   shadow = 2;
   colorText[] = {0,1,0,1};
   font = "puristaMedium";
   sizeEx = 0.02;
   colorBackground[] = { 0,0,0, 0.8 };
   text = "";
};
class RscText {
    deletable = 0;
    fade = 0;
    access = 0;
    type = CT_STATIC;
    idc = -1;
    colorBackground[] = {0,0,0,0};
    colorText[] = {1,1,1,1};
    text = "";
    fixedWidth = 0;
    x = 0;
    y = 0;
    h = 0.037;
    w = 0.3;
    style = ST_LEFT;
    shadow = 1;
    colorShadow[] = {0,0,0,0.5};
    font = "RobotoCondensed";
    SizeEx = GUI_TEXT_SIZE_MEDIUM;
    linespacing = 1;
    tooltipColorText[] = {1,1,1,1};
    tooltipColorBox[] = {1,1,1,1};
    tooltipColorShade[] = {0,0,0,0.65};
};
class RscControlsGroup {
    deletable = 0;
    fade = 0;
    class VScrollbar: ScrollBar {
        color[] = {1,1,1,1};
        width = 0.021;
        autoScrollEnabled = 1;
    };
    class HScrollbar: ScrollBar {
        color[] = {1,1,1,1};
        height = 0.028;
    };
    class Controls {
    };
    type = CT_CONTROLS_GROUP;
    idc = -1;
    x = 0;
    y = 0;
    w = 1;
    h = 1;
    shadow = 0;
    style = ST_MULTI;
};
class RscControlsGroupNoScrollbars: RscControlsGroup {
    class VScrollbar: VScrollbar {
        width = 0;
    };
    class HScrollbar: HScrollbar {
        height = 0;
    };
};
class RscProgress {
    deletable = 0;
    fade = 0;
    access = 0;
    type = CT_PROGRESS;
    style = ST_HORIZONTAL;
    colorFrame[] = {0,0,0,0};
    colorBar[] = {
        "(profilenamespace getvariable ['GUI_BCG_RGB_R',0.13])",
        "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.54])",
        "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.21])",
        "(profilenamespace getvariable ['GUI_BCG_RGB_A',0.8])"
    };
    x = 0.344;
    y = 0.619;
    w = 0.313726;
    h = 0.0261438;
    shadow = 2;
    texture = "#(argb,8,8,3)color(1,1,1,1)";
};
class RscVProgress: RscProgress {
    style = ST_VERTICAL;
};
